language: node_js
os:
    - linux
    - windows
node_js:
    - "stable"
    - "6.9.5"
    - "4.0.0"
sudo: false    
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
